import 'reflect-metadata';
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { test } from 'node:test';
import { Global, Module, UnauthorizedException, ValidationPipe } from '@nestjs/common';
import { APP_GUARD, NestFactory } from '@nestjs/core';
import { FastifyAdapter, type NestFastifyApplication } from '@nestjs/platform-fastify';
import { PGlite } from '@electric-sql/pglite';
import { drizzle } from 'drizzle-orm/pglite';
import { count, eq } from 'drizzle-orm';
import * as schema from '../src/database/schema/index.js';
import { DatabaseService } from '../src/database/database.service.js';
import { ValuationModule } from '../src/modules/valuation/valuation.module.js';
import { ValuationAdminService } from '../src/modules/valuation/valuation.service.js';
import { ValuationRepository } from '../src/modules/valuation/valuation.repository.js';
import { DEFAULT_CONFIG } from '../src/modules/valuation/defaults.js';
import { VALUATION_PERMISSIONS } from '../src/modules/valuation/domain.js';
import { seedValuation } from '../src/database/seed/valuation.js';
import { JwtAuthGuard } from '../src/modules/auth/jwt-auth.guard.js';
import { JwtVerifierService } from '../src/modules/auth/jwt-verifier.service.js';
import { PermissionsGuard } from '../src/modules/auth/permissions.guard.js';
import { AdminAccessService } from '../src/modules/auth/admin-access.service.js';
import { ApiExceptionFilter } from '../src/common/filters/api-exception.filter.js';
import { PinoLoggerService } from '../src/common/logging/pino-logger.service.js';
import { CatalogService } from '../src/modules/catalog/catalog.service.js';
import { LookupsService } from '../src/modules/lookups/lookups.service.js';

test('valuation Phase 1: migrations, idempotent draft seed, CRUD validation, RBAC, atomic policy lifecycle and audit', async () => {
  const pg = new PGlite(); let app: NestFastifyApplication | undefined;
  try {
    for (const file of (await readdir('drizzle')).filter(file => file.endsWith('.sql')).sort()) await pg.exec((await readFile(`drizzle/${file}`, 'utf8')).replaceAll('--> statement-breakpoint', ''));
    const rawDb = drizzle(pg, { schema }), db = rawDb as unknown as DatabaseService['db'];
    const [profile] = await db.insert(schema.profiles).values({ authUserId: '49332fa0-8244-4b20-a8d0-9793b72ef689', fullName: 'Valuation test' }).returning();
    await db.insert(schema.roles).values([{ code: 'ADMIN', name: 'Admin' }, { code: 'SALES', name: 'Sales' }, { code: 'CONTENT_EDITOR', name: 'Editor' }]);
    const first = await seedValuation(db); assert.equal(first.created, true);
    const snapshotCounts = async () => ({ options: (await db.select({ total: count() }).from(schema.valuationOptions))[0].total, rules: (await db.select({ total: count() }).from(schema.valuationRules))[0].total });
    const before = await snapshotCounts(); assert.ok(before.options >= 40); assert.ok(before.rules > before.options);
    assert.equal((await seedValuation(db)).created, false); assert.deepEqual(await snapshotCounts(), before);
    assert.equal((await db.select().from(schema.valuationSettings))[0].isEnabled, false);
    assert.equal((await db.select().from(schema.valuationPolicies))[0].status, 'DRAFT');
    assert.equal((await db.select().from(schema.valuationReferencePrices)).length, 0);
    const assignments = await db.select({ role: schema.roles.code, permission: schema.permissions.code }).from(schema.rolePermissions).innerJoin(schema.roles, eq(schema.rolePermissions.roleId, schema.roles.id)).innerJoin(schema.permissions, eq(schema.rolePermissions.permissionId, schema.permissions.id));
    assert.deepEqual(assignments.filter(row => row.role === 'SALES').map(row => row.permission).sort(), ['valuation.read', 'valuation.history.read', 'valuation.history.update'].sort());
    assert.equal(assignments.filter(row => row.role === 'CONTENT_EDITOR').length, 0);
    const database = { db } as DatabaseService;
    const repo = new ValuationRepository(database), service = new ValuationAdminService(repo);
    @Global() @Module({ imports: [ValuationModule], providers: [
      { provide: DatabaseService, useValue: database },
      { provide: JwtVerifierService, useValue: { verify: async (token: string) => { if (!['admin', 'reader', 'outsider'].includes(token)) throw new UnauthorizedException(); return { id: token }; } } },
      { provide: AdminAccessService, useValue: { forAuthUser: async (id: string) => ({ profile, roles: ['ADMIN'], permissions: id === 'admin' ? VALUATION_PERMISSIONS : id === 'reader' ? ['valuation.read'] : [] }) } },
      { provide: APP_GUARD, useClass: JwtAuthGuard }, { provide: APP_GUARD, useClass: PermissionsGuard },
    ], exports: [DatabaseService] }) class TestModule {}
    app = await NestFactory.create<NestFastifyApplication>(TestModule, new FastifyAdapter(), { logger: false });
    app.setGlobalPrefix('api/v1'); app.useGlobalPipes(new ValidationPipe({ whitelist: true, forbidNonWhitelisted: true, transform: true }));
    app.useGlobalFilters(new ApiExceptionFilter(new PinoLoggerService()));
    await app.init(); await app.getHttpAdapter().getInstance().ready();
    const server = app.getHttpAdapter().getInstance();
    const send = (method: 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE', path: string, payload?: object, token = 'admin') => server.inject({ method, url: `/api/v1/admin/valuation/${path}`, ...(payload ? { payload } : {}), headers: token ? { authorization: `Bearer ${token}` } : {} });
    assert.equal((await send('GET', 'overview', undefined, '')).statusCode, 401);
    assert.equal((await send('GET', 'overview', undefined, 'outsider')).statusCode, 403);
    assert.equal((await send('GET', 'overview', undefined, 'reader')).statusCode, 200);
    assert.equal((await send('POST', 'policies', { name: 'Test', version: '1.0.0', reason: 'Fixture' }, 'reader')).statusCode, 403);
    assert.equal((await send('GET', 'audit', undefined, 'reader')).statusCode, 403);
    assert.equal((await send('POST', 'policies', { name: 'Test', version: '1.0.0', reason: 'Fixture', unknownField: true })).statusCode, 400);
    const created = await send('POST', 'policies', { name: 'Test rules', version: '1.0.0', reason: 'Isolated synthetic fixture' }); assert.equal(created.statusCode, 201); const policyId = created.json().id as string;
    const revision = async () => (await repo.policy(policyId)).revision;
    const check = async () => (await send('POST', `policies/${policyId}/validate`, { expectedRevision: await revision(), reason: 'Validate test master data' })).json();
    assert.equal((await check()).report.passed, false);
    assert.equal((await send('POST', `policies/${policyId}/publish`, { expectedRevision: await revision(), reason: 'Reject unvalidated policy', confirmed: true })).statusCode, 409);
    const [brand] = await db.insert(schema.brands).values({ name: 'Test brand', slug: 'test-brand' }).returning();
    const [model] = await db.insert(schema.carModels).values({ brandId: brand.id, name: 'Test model', slug: 'test-model' }).returning();
    const [variant] = await db.insert(schema.carVersions).values({ modelId: model.id, name: 'Test variant', slug: 'test-variant' }).returning();
    const reference = { policyId, variantId: variant.id, modelYear: 2022, basePriceType: 'ORIGINAL_MSRP', originalMsrp: 900000000, source: 'Synthetic fixture, not a market source', note: '', basisNote: '', active: true, effectiveFrom: '2020-01-01T00:00:00+07:00', reason: 'Enter isolated fixture price' };
    assert.equal((await send('POST', 'reference-prices', { ...reference, originalMsrp: null, expectedRevision: await revision() })).statusCode, 400);
    assert.equal((await send('POST', 'reference-prices', { ...reference, originalMsrp: 0, expectedRevision: await revision() })).statusCode, 400);
    assert.equal((await send('POST', 'reference-prices', { ...reference, effectiveTo: '2019-01-01', expectedRevision: await revision() })).statusCode, 400);
    assert.equal((await send('POST', 'reference-prices', { ...reference, basePriceType: 'MARKET_REFERENCE', marketReference: 600000000, expectedRevision: await revision() })).statusCode, 400);
    const saved = await send('POST', 'reference-prices', { ...reference, expectedRevision: await revision() }); assert.equal(saved.statusCode, 201); const referenceId = saved.json().id;
    assert.equal(saved.json().updatedBy, profile.id);
    assert.equal((await send('POST', 'reference-prices', { ...reference, expectedRevision: await revision() })).statusCode, 400);
    assert.equal((await send('PATCH', `reference-prices/${referenceId}`, { ...reference, expectedRevision: 1 })).statusCode, 409);
    const temporaryReference = { ...reference, modelYear: 2021, active: false };
    const temporaryPrice = await send('POST', 'reference-prices', { ...temporaryReference, expectedRevision: await revision() }); assert.equal(temporaryPrice.statusCode, 201);
    assert.equal((await send('PATCH', `reference-prices/${temporaryPrice.json().id}`, { ...temporaryReference, originalMsrp: 910000000, expectedRevision: await revision() })).statusCode, 200);
    assert.equal((await send('DELETE', `reference-prices/${temporaryPrice.json().id}`, { expectedRevision: await revision(), reason: 'Remove unused fixture price' })).statusCode, 204);
    const priceList = (await send('GET', `reference-prices?policyId=${policyId}&brandId=${brand.id}&search=test&limit=1`)).json();
    assert.equal(priceList.meta.total, 1); assert.equal(priceList.data[0].selectedBasePrice, 900000000); assert.equal(priceList.data[0].brandName, 'Test brand');
    assert.equal((await send('GET', 'reference-prices?limit=500')).statusCode, 400);
    const invalidConfig = { ...DEFAULT_CONFIG, dealerMarginMinPercent: 10, dealerMarginMaxPercent: 5 };
    assert.equal((await send('PATCH', `policies/${policyId}`, { name: 'Invalid config', config: invalidConfig, expectedRevision: await revision(), reason: 'Test margin validation' })).statusCode, 400);
    assert.equal((await send('PATCH', `policies/${policyId}`, { name: 'Invalid nested config', config: { ...DEFAULT_CONFIG, confidenceWeights: { ...DEFAULT_CONFIG.confidenceWeights, hacked: 1 } }, expectedRevision: await revision(), reason: 'Test nested whitelist' })).statusCode, 400);
    assert.equal((await send('PATCH', `policies/${policyId}`, { name: 'Invalid array config', config: [DEFAULT_CONFIG], expectedRevision: await revision(), reason: 'Test object shape' })).statusCode, 400);
    const rule = { policyId, category: 'AGE', scope: 'GLOBAL', minValue: 5, maxValue: 6, adjustmentPercent: -20, manualInspectionRequired: false, active: true, label: 'Overlap', note: '', reason: 'Test overlapping band' };
    assert.equal((await send('POST', 'rules', { ...rule, expectedRevision: await revision() })).statusCode, 400);
    assert.equal((await send('POST', 'rules', { ...rule, scope: 'BRAND', brandId: brand.id, modelId: model.id, expectedRevision: await revision() })).statusCode, 400);
    const specific = await send('POST', 'rules', { ...rule, scope: 'BRAND', brandId: brand.id, expectedRevision: await revision() }); assert.equal(specific.statusCode, 201);
    assert.equal((await send('POST', 'rules', { ...rule, scope: 'BRAND', brandId: brand.id, minValue: 6, maxValue: 7, expectedRevision: await revision() })).statusCode, 201, 'Adjacent bands must be accepted');
    const temporaryRule = await send('POST', 'rules', { ...rule, active: false, expectedRevision: await revision() }); assert.equal(temporaryRule.statusCode, 201);
    assert.equal((await send('PATCH', `rules/${temporaryRule.json().id}`, { ...rule, active: false, adjustmentPercent: -21.5, expectedRevision: await revision() })).statusCode, 200);
    assert.equal((await send('DELETE', `rules/${temporaryRule.json().id}`, { expectedRevision: await revision(), reason: 'Remove unused fixture rule' })).statusCode, 204);
    const temporaryOption = { policyId, category: 'EXTERIOR', code: 'TEMPORARY', label: 'Temporary fixture', description: '', isUnknown: false, requiresInspection: false, active: false, sortOrder: 99, reason: 'Create temporary fixture option' };
    const optionCreated = await send('POST', 'options', { ...temporaryOption, expectedRevision: await revision() }); assert.equal(optionCreated.statusCode, 201);
    assert.equal((await send('PATCH', `options/${optionCreated.json().id}`, { ...temporaryOption, label: 'Updated temporary fixture', expectedRevision: await revision() })).statusCode, 200);
    assert.equal((await send('DELETE', `options/${optionCreated.json().id}`, { expectedRevision: await revision(), reason: 'Remove unused fixture option' })).statusCode, 204);
    const own = await repo.snapshot(policyId), foreign = await repo.snapshot(first.policyId);
    const flood = own.options.find(option => option.code === 'HYDROLOCK' && option.category === 'FLOOD')!;
    assert.equal((await send('POST', 'rules', { ...rule, category: 'FLOOD', scope: 'BRAND', brandId: brand.id, minValue: null, maxValue: null, optionId: flood.id, expectedRevision: await revision() })).statusCode, 400, 'Severe condition cannot disable manual inspection');
    assert.equal((await send('POST', 'rules', { ...rule, category: 'FLOOD', minValue: null, maxValue: null, optionId: foreign.options[0].id, expectedRevision: await revision() })).statusCode, 400, 'Cross-policy option rejected');
    assert.equal((await send('DELETE', `options/${flood.id}`, { expectedRevision: await revision(), reason: 'Reject deletion of referenced option' })).statusCode, 409);
    const inspectionOption = own.options.find(option => option.category === 'EXTERIOR' && !option.requiresInspection)!;
    const { id: optionId, createdAt: _created, updatedAt: _updated, updatedBy: _updater, ...optionFields } = inspectionOption;
    void _created; void _updated; void _updater;
    assert.equal((await send('PATCH', `options/${optionId}`, { ...optionFields, requiresInspection: true, expectedRevision: await revision(), reason: 'Require inspection and audit dependent rules' })).statusCode, 200);
    const affectedRule = own.rules.find(row => row.optionId === optionId)!;
    assert.equal((await repo.snapshot(policyId)).rules.find(row => row.id === affectedRule.id)!.manualInspectionRequired, true);
    assert.ok((await send('GET', 'audit?limit=100')).json().data.some((row: { action: string; entityId: string }) => row.action === 'valuation.rule.update' && row.entityId === affectedRule.id));
    // Persistence checks operate below DTO validation as well.
    await assert.rejects(() => db.insert(schema.valuationRules).values({ policyId, category: 'MARKET', scope: 'GLOBAL', label: 'Unsafe', adjustmentPercent: -100 }));
    await assert.rejects(() => db.insert(schema.valuationReferencePrices).values({ policyId, variantId: variant.id, modelYear: 2022, basePriceType: 'ORIGINAL_MSRP', originalMsrp: -1, source: 'Invalid DB price', effectiveFrom: new Date() }));
    const passed = await check(); assert.equal(passed.report.passed, true, JSON.stringify(passed.report));
    const currentRevision = await revision();
    await db.update(schema.brands).set({ status: 'inactive' }).where(eq(schema.brands.id, brand.id));
    assert.equal((await send('POST', `policies/${policyId}/publish`, { expectedRevision: currentRevision, reason: 'Catalog changed since validation', confirmed: true })).statusCode, 409);
    await db.update(schema.brands).set({ status: 'active' }).where(eq(schema.brands.id, brand.id));
    assert.equal((await send('POST', `policies/${policyId}/publish`, { expectedRevision: currentRevision, reason: 'Reject absent confirmation', confirmed: false })).statusCode, 400);
    const published = await send('POST', `policies/${policyId}/publish`, { expectedRevision: currentRevision, reason: 'Publish fixture master data only', confirmed: true }); assert.equal(published.statusCode, 201);
    assert.equal((await repo.settings()).activePolicyId, policyId); assert.equal((await repo.settings()).isEnabled, false);
    assert.equal((await send('PATCH', `reference-prices/${referenceId}`, { ...reference, originalMsrp: 950000000, expectedRevision: currentRevision })).statusCode, 409);
    assert.equal((await send('DELETE', `rules/${specific.json().id}`, { expectedRevision: currentRevision, reason: 'Reject deleting published rule' })).statusCode, 409);
    const settings = await repo.settings();
    assert.equal((await send('PUT', 'settings', { isEnabled: true, disclaimer: settings.disclaimer, ctaLabel: settings.ctaLabel, expectedUpdatedAt: settings.updatedAt.toISOString(), reason: 'Activation needs explicit data review' })).statusCode, 400);
    const clone = await send('POST', `policies/${policyId}/clone`, { name: 'Clone', version: '1.1.0', reason: 'Check immutable clone' }); assert.equal(clone.statusCode, 201); const cloneId = clone.json().id;
    const cloneSnapshot = await repo.snapshot(cloneId); assert.equal(cloneSnapshot.policy.status, 'DRAFT'); assert.equal(cloneSnapshot.references[0].originalMsrp, 900000000);
    assert.ok(cloneSnapshot.rules.every(row => !row.optionId || cloneSnapshot.options.some(option => option.id === row.optionId)));
    const audit = { actorProfileId: profile.id, ipAddress: '127.0.0.1', userAgent: null, requestId: 'fixture' };
    await service.updatePolicy(cloneId, { name: 'Clone changed', expectedRevision: 1, config: { ...DEFAULT_CONFIG, dealerMarginMinPercent: 3 }, reason: 'Test invalidation after validation' }, audit);
    await assert.rejects(() => service.publish(cloneId, { expectedRevision: 2, confirmed: true, reason: 'Reject not revalidated clone' }, audit));
    const catalogService = new CatalogService(database), lookups = new LookupsService(database);
    const [otherBrand] = await db.insert(schema.brands).values({ name: 'Other', slug: 'other' }).returning();
    const [otherModel] = await db.insert(schema.carModels).values({ brandId: otherBrand.id, name: 'Other model', slug: 'other-model' }).returning();
    await assert.rejects(() => catalogService.updateModel(model.id, { brandId: otherBrand.id }), /định giá/);
    await assert.rejects(() => lookups.update('car-versions', variant.id, { modelId: otherModel.id }, audit), /định giá/);
    const clonedCheck = await service.validate(cloneId, { expectedRevision: 2, reason: 'Validate cloned policy' }, audit); assert.equal(clonedCheck.report.passed, true);
    await service.publish(cloneId, { expectedRevision: 2, confirmed: true, reason: 'Publish replacement fixture' }, audit);
    assert.equal((await repo.policy(policyId)).status, 'ARCHIVED'); assert.equal((await repo.settings()).activePolicyId, cloneId);
    await service.archive(cloneId, { expectedRevision: 2, reason: 'Archive fixture policy' }, audit);
    assert.equal((await repo.settings()).activePolicyId, null);
    assert.ok((await send('GET', 'audit?limit=100')).json().data.some((row: { action: string }) => row.action === 'valuation.policy.publish'));
    assert.equal((await server.inject({ method: 'GET', url: '/api/v1/valuation/brands' })).statusCode, 503, 'Public utility remains disabled until release');
  } finally { if (app) await app.close(); await pg.close(); }
});
