import type { RuleDefinition } from './domain.js';

export const INITIAL_RULES: (Omit<RuleDefinition, 'id'> & { title: string; description: string })[] = [
  { code: 'DIRECT_AGE_CONFLICT', engineHandler: 'DIRECT_AGE_CONFLICT', category: 'COMPATIBILITY', priority: 'CRITICAL', effect: 'NEGATIVE', weight: 40, hardExclusion: true, isEnabled: true, sortOrder: 0, parameters: {}, title: 'Ngày xung trực tiếp với tuổi', description: 'Địa chi của ngày đối xung với địa chi năm sinh âm lịch. Quy tắc cần được xác minh nguồn trước khi áp dụng.' },
  { code: 'BRANCH_HARMONY', engineHandler: 'BRANCH_HARMONY', category: 'COMPATIBILITY', priority: 'MEDIUM', effect: 'POSITIVE', weight: 10, hardExclusion: false, isEnabled: true, sortOrder: 1, parameters: {}, title: 'Ngày có quan hệ hợp với tuổi', description: 'Địa chi của ngày thuộc lục hợp hoặc cùng nhóm tam hợp với địa chi năm sinh âm lịch.' },
  { code: 'TRADITIONAL_TABOO', engineHandler: 'TRADITIONAL_TABOO', category: 'ALMANAC', priority: 'CRITICAL', effect: 'NEGATIVE', weight: 40, hardExclusion: true, isEnabled: true, sortOrder: 2, parameters: {}, title: 'Ngày kiêng theo quan niệm truyền thống', description: 'Ngày âm lịch thuộc danh sách Tam nương hoặc Nguyệt kỵ. Đây là thông tin tham khảo, cần xác minh nguồn.' },
  { code: 'AUSPICIOUS_DAY', engineHandler: 'AUSPICIOUS_DAY', category: 'ALMANAC', priority: 'MEDIUM', effect: 'POSITIVE', weight: 15, hardExclusion: false, isEnabled: true, sortOrder: 3, parameters: {}, title: 'Ngày hoàng đạo', description: 'Ngày thuộc nhóm hoàng đạo theo địa chi ngày và tháng âm lịch.' },
  { code: 'PURPOSE_OFFICER', engineHandler: 'PURPOSE_OFFICER', category: 'PURPOSE', priority: 'HIGH', effect: 'POSITIVE', weight: 15, hardExclusion: false, isEnabled: false, sortOrder: 4, parameters: { officers: [] }, title: 'Trực phù hợp với mục đích', description: 'TODO(BUSINESS-RULE): nhập danh sách Trực được tài liệu đã xác minh cho phép đối với mục đích này; không tự suy đoán danh sách.' },
  { code: 'FIVE_ELEMENT_RELATION', engineHandler: 'FIVE_ELEMENT_RELATION', category: 'COMPATIBILITY', priority: 'MEDIUM', effect: 'POSITIVE', weight: 10, hardExclusion: false, isEnabled: false, sortOrder: 5, parameters: {}, title: 'Quan hệ ngũ hành tham khảo', description: 'So sánh ngũ hành nạp âm của ngày với nạp âm năm sinh; không suy diễn từ con giáp.' },
  { code: 'GOOD_HOURS', engineHandler: 'GOOD_HOURS', category: 'ALMANAC', priority: 'LOW', effect: 'NEUTRAL', weight: 0, hardExclusion: false, isEnabled: false, sortOrder: 6, parameters: {}, title: 'Giờ hoàng đạo tham khảo', description: 'Bảng giờ hoàng đạo theo địa chi ngày; cần xác minh nguồn trước khi bật hiển thị giờ.' },
];
